name: Build and Test CVI 2019 Project

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  # Build CVI project
  Build_CVI_Project:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build CVI project
      run: .\build_prj.bat

  # Build unit test project
  Build_Unit_Tests:
    needs: Build_CVI_Project
    runs-on: self-hosted

    steps:
    - name: Build unit tests
      run: .\build_tests.bat

  # Run unit test executable
  Run_Unit_Tests:
    needs: Build_Unit_Tests
    runs-on: self-hosted

    steps:
    - name: Run unit tests
      run: .\run_tests.bat

  # Upload artifacts
  Upload_Artifacts:
    needs: Run_Unit_Tests
    runs-on: self-hosted

    steps:
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CVI-Build-Output
        path: |
          *.dll
          *.lib
          *.h
